repos:

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    - id: autoflake
      args: [
        --in-place,
        --remove-unused-variables,
        --remove-all-unused-imports,
      ]

  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
    - id: yapf
      args: [
        --in-place
      ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
    - id: mypy
      additional_dependencies:
        - types-requests
      args: [
        --strict,
        --ignore-missing-imports,
        --allow-untyped-decorators,
        --allow-subclassing-any
      ]

  - repo: https://github.com/pycqa/pydocstyle
    rev: 4.0.0
    hooks:
    - id: pydocstyle
      args: [
        '--ignore=D213,D203,D204,D416'
      ]

  - repo: local
    hooks:
    - id: pycodestyle
      name: pycodestyle
      entry: pycodestyle
      language: system
      args: [
        '--ignore=E722,E126',
        '--max-line-length=80',
        '--exclude=*init*'
      ]
      files: \.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: check-docstring-first
    - id: check-added-large-files
    - id: check-yaml
      args: [--allow-multiple-documents]
